### PR TITLE
Pedestrian amd64

### PR DESCRIPTION
**Pull request by alpha-carinae29**
2 pedestrian detection model added, these models are trained with Oxford Town Center Dataset and TensorFlow Object Detection API.
Also I have trained a Faster RCNN ResNet 50 model that I couldn't since the `.pb` files was more than 100MB.

### CODE REVIEW

**Comment by mhejrati** [comment]
Have you tried git LFS? 
https://help.github.com/en/github/managing-large-files/about-git-large-file-storage

We currently have 1GB included with the github account and if need be we can increase that.

**Comment by alpha-carinae29** [comment]
> Have you tried git LFS?

yeah but you should have at least one LFS object on root directory so other public forks can push LFS objects.
https://github.com/git-lfs/git-lfs/issues/1449#issuecomment-239831273

**Comment by mhejrati** [comment]
@alpha-carinae29 
You should be able to try LFS now

**Comment by alpha-carinae29** [comment]
thanks @mhejrati
I added the Faster RCNN model. You can merge it now.

**Review by mhejrati — APPROVED** [review]
LGTM

**Pull request merged**
